const express = require('express')
const router = express.Router()
const cp_controller = require('../controllers/cp_controllers')
const auth = require('../controllers/auth_controllers')
// ,auth.authenMid,auth.verifyUser,
router.use(auth.authenMid,auth.verifyUser,auth.CPvalidation)

router.patch('/transport/process',auth.closedRejection,cp_controller.transport)
router.patch('/transport',cp_controller.twoLandsResources)
router.patch('/buy',auth.closedRejection,cp_controller.buy)
router.post('/plant',cp_controller.getPlant)
router.patch('/plant/process',auth.closedRejection,cp_controller.plant)
router.patch('/transport/process',auth.closedRejection,cp_controller.transport)
router.patch('/watering',auth.closedRejection,cp_controller.watering)
router.patch('/feeding/process',auth.closedRejection,cp_controller.feeding)
router.get('/kadrAttack',auth.closedRejection,cp_controller.getAttackKadr)
router.post('/buy',cp_controller.getBuy)
router.patch('/attack',auth.closedRejection,cp_controller.attack)
router.patch('/patrolAttack',cp_controller.getAttackPatrol)
router.patch('/feeding',cp_controller.checkLandNo)
router.post('/feeding',cp_controller.getFeeding)    
router.get('/',cp_controller.getPatrol) 
router.post('/attack',cp_controller.checkAttack)
router.post('/attack/kadr',auth.closedRejection, cp_controller.attackKadr)

module.exports = router